### ISSUE TITLE
lxi-tools logo looks skewed on Windows

### ISSUE THREAD

**Issue by lundmar** [lxi-tools/lxi-tools-windows-installer#2]
@psalic 

The lxi-tools logo in the About dialog looks skewed compared to linux version:

![Screenshot From 2024-10-01 19-31-00](https://github.com/user-attachments/assets/a9fd5a94-7e1d-4b2e-8645-b43a3b8fb226)

I assume this is an effect of the newly introduce convert step. Perhaps some fine tuning is required or maybe use a different conversion tool.

**Comment by psalic** [comment]
No. It uses original svg file. First I forget to add it and was empty space.

**Comment by lundmar** [comment]
Hmmm, so maybe a gtk svg rendering issue in cygwin/windows. I assume you are using recent a version of gtk?

**Comment by psalic** [comment]
It same version of gtk4 on debian testing and it look normal.

**Comment by lundmar** [comment]
Ok, I'll assume this is a rendering engine issue under Windows. Not a big issue. Closing.

**Comment by psalic** [comment]
I really don't have idea why this happen.
